image: Visual Studio 2022
skip_tags: true
platform: 
- x86
- x64
configuration: Debug

before_build:
  - nuget restore

after_build: "7z a Build_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\\Memory\\bin\\%PLATFORM%\\Debug\\*.nupkg %APPVEYOR_BUILD_FOLDER%\\Memory\\bin\\%PLATFORM%\\Debug\\netstandard2.1\\*.dll %APPVEYOR_BUILD_FOLDER%\\Memory\\bin\\%PLATFORM%\\Debug\\netstandard2.1\\*.xml %APPVEYOR_BUILD_FOLDER%\\Memory\\bin\\%PLATFORM%\\Debug\\netstandard2.1\\*.json %APPVEYOR_BUILD_FOLDER%\\Memory\\bin\\%PLATFORM%\\Debug\\netstandard2.1\\*.pdb"

build:
  project: Memory.sln

artifacts:
  path: Build_%PLATFORM%.zip
  name: Latest

branches:
  only:
    - master

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_BUILD_ID)
    release: Build $(APPVEYOR_REPO_COMMIT_TIMESTAMP)
    description: Latest Compile Date %APPVEYOR_REPO_COMMIT_TIMESTAMP%
    auth_token:
      secure: y+vnpDslJlfpQVrm2NaPq4dZR9T5yD/e+Z4fKna+fq9m25G3THlrUVp35pCTRc2lS+BmGxxQVhDLNN5EgmQQeERYgVSdPNsbD7GgGFlHrO2Yxl/EX1WXAGBzCRYlnT5Y
    artifact: Build_%PLATFORM%.zip
    force_update: true
    draft: false
